# mainSections = ["post", "posts"] # Default to ["posts"].

# titleSeparator = "|" # Title separator. Default to "-".

description = "Euraxluo Blog,Some post about python,cpp,go,java."
# image = ["site-feature-image.jpg"]

logo = "https://gitee.com/Euraxluo/images/raw/master/picgo/profile.png" # Logo image. Default to "images/logo.webp".
brand = "Euraxluo"
#menusPosition = "left" # Menus position: right(default), left or center.

palette = "blue" # Default palette. Optional.
# palettes = ["blue", "blue gray", "brown"] # Available palettes. Default to ALL.

# fullWidth = true # Full width.

# dateFormat = "Jan 2, 2006"

# Google Adsense
googleAdsense = ""

# math = true # Enable math globally.
# toc = false # Disable TOC globally.
# breadcrumb = false # Disable breadcrumb

# poweredBy = false # Whether to show powered by.

# featuredPostCount = 10 # The number of featured posts shown in sidebar.
# recentPostCount = 10 # The number of recent posts shown in sidebar.
# relatedPostCount = 10 # The number of related posts.
# categoryCount = 10 # The number of categories shown in sidebar.
# tagCount = 10 # The number of tags shown in sidebar.
# seriesCount = 10 # The number of series shown in sidebar.

# Custom CSS and JS
customCSS = []
customJS = []

# tocWordCount = 280 # TOC is displayed only if the post's word count exceeds this value.
# tocSticky = true # Whether to make TOC stick to top when scrolling. Default to true.

[archive]
  paginate = 8 # Archive pagination. Default to 100.
  # dateFormat = "01-02" # Archive date format. Default to "Jan 2".

[analytics]
  # baidu = "" # Baidu Analytics

# Site verification
[siteVerification]
  google = ""
  bing = ""
  baidu = ""
  baiduUnion = "" # Baidu Union
  so = ""
  sogou = ""
  shenma = ""

[creativeCommons]
  # by = true # Credit must be given to you, the creator.
  # nc = true # Only noncommercial use of your work is permitted.
  # nd = true # No derivatives or adaptations of your work are permitted.
  # sa = true # Adaptations must be shared under the same terms.

[utterances]
  # https://utteranc.es/
  crossorigin="anonymous"
  repo="Euraxluo/Euraxluo.github.io"
  issue-term="pathname"
  label="âœ¨ðŸ’¬âœ¨"
  theme="github-dark"
        


[search]
  paginate = 5 # Pagination. Default to 10.
  # resultContentWordCount = 240 # The maximum word count of result content for displaying.
  # Fuse.js options. See https://fusejs.io/api/options.html.
  [search.fuse]
    # ignoreLocation = true
    # location = 0
    # isCaseSensitive = false
    # minMatchCharLength = 1
    threshold = 0.1
    # distance = 100
    # useExtendedSearch = true

[reward]
  alipay = "https://gitee.com/Euraxluo/images/raw/master/picgo/_alipay.jpg"
  wechat = "https://gitee.com/Euraxluo/images/raw/master/picgo/_wechatpay.jpg"

[share]
  # addThis = "" # AddThis pubid.

[fontSize]
  # extraSmall = ".8rem"
  # small = ".9rem"
  # large = "1.1rem"
  # extraLarge = "1.2rem"
